import { loadPatient } from "@/data/loadPatient";
import { loadHopeSeizures } from "@/data/loadSeizures";
import { loadHopeVideos } from "@/data/loadVideos";
import { loadMedications } from "@/data/loadMedications";
import { loadLaboratory } from "@/data/loadLaboratory";
import CasePanorama from "@/components/CasePanorama";
import { loadClinicalEvents } from "@/data/loadClinicalEvents";


import {
  buildReferralData,
  type ReferralData,
} from "@/data/buildReferralData";

type Props = {
  params: Promise<{
    id: string;
  }>;
};

type ReferralMedication =
  ReferralData["medications"][number];



export default async function ReferralPage({
  params,
}: Props) {
  const { id } = await params;


  const patient = loadPatient();

  if (patient.id !== id) {
    return (
      <main className="flex min-h-screen items-center justify-center">
        <h1 className="text-3xl font-bold text-red-600">
          Patient not found
        </h1>
      </main>
    );
  }

  const seizures = loadHopeSeizures();
  const videos = loadHopeVideos();
  const medications = loadMedications();
  const laboratory = loadLaboratory();
  const clinicalEvents = loadClinicalEvents();

  const referral = buildReferralData(
    patient,
    seizures,
    videos,
    medications,
    laboratory,
    clinicalEvents
 );

  /*
   * Presentation groups only.
   * Underlying medication evidence remains unchanged.
   */

  const levetiracetam = referral.medications.filter(
    (medication) =>
      medication.activeIngredient?.toLowerCase() ===
        "levetiracetam" ||
      medication.name.toLowerCase() === "levetiracetam"
  );

  const phenobarbital = referral.medications.filter(
    (medication) =>
      medication.activeIngredient?.toLowerCase() ===
        "phenobarbital"
  );

  const emergencyPlan = referral.medications.filter(
    (medication) =>
      medication.status ===
      "current-emergency-plan"
  );

  /*
   * Current regimen text is generated from medication evidence.
   * The UI does not duplicate dose/schedule values.
   */

  const getCurrentMedication = (
  medicationRecords: ReferralMedication[],
  statuses: string[]
) =>
  medicationRecords.find(
    (medication) =>
      medication.status &&
      statuses.includes(medication.status)
  );

  const getCurrentMedicationText = (
    medicationRecords: ReferralMedication[],
    statuses: string[]
  ) => {
    const current = getCurrentMedication(
      medicationRecords,
      statuses
    );

    if (!current) {
      return "Current regimen not available.";
    }

    return current.frequency || current.dose;
  };

  return (
    <main className="min-h-screen bg-slate-100 px-6 py-10">
      <article className="mx-auto max-w-5xl rounded-xl bg-white p-8 shadow-lg">

        {/* PRINT HEADER */}

        <div className="hidden print:block print:mb-4">
          <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">
            Prepared for specialist review
          </p>

          <p className="mt-1 text-xs text-slate-500">
            Generated by Compass Clinical
          </p>
        </div>

        {/* HEADER */}

        <header className="border-b border-slate-200 pb-6">
          <p className="text-sm font-medium uppercase tracking-wide text-slate-500">
            Compass Clinical Referral
          </p>

          <h1 className="mt-2 text-4xl font-bold text-slate-900">
            {referral.patientName}
          </h1>

          <p className="mt-2 text-slate-600">
            {referral.species} · {referral.breed} ·{" "}
            {referral.sex}
          </p>

          <p className="mt-1 text-sm text-slate-500">
            Patient ID: {referral.patientId}
          </p>
        </header>

        {/* REASON FOR REFERRAL */}

        <section className="mt-8">
          <h2 className="text-xl font-semibold text-slate-900">
            Reason for specialist review
          </h2>

          <p className="mt-2 leading-7 text-slate-700">
            {referral.clinicalProblem}
          </p>

          {referral.workingDiagnosis && (
            <p className="mt-2 text-sm text-slate-600">
              Working diagnosis:{" "}
              <strong>
                {referral.workingDiagnosis}
              </strong>
            </p>
          )}
        </section>

        {/* SEIZURE SUMMARY */}

        <section className="mt-8">
          <h2 className="text-xl font-semibold text-slate-900">
            Seizure diary summary
          </h2>

          <div className="print-compact-grid mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            <Metric
              label="Logged events"
              value={
                referral.seizureDiary.totalLoggedEvents
              }
            />

            <Metric
              label="Unique event days"
              value={
                referral.seizureDiary.uniqueEventDays
              }
            />

            <Metric
              label="Multi-event days"
              value={
                referral.seizureDiary.multiEventDays
              }
            />

            <Metric
              label="Maximum events/day"
              value={
                referral.seizureDiary.maxEventsInOneDay
              }
            />

            <Metric
              label="Diary start"
              value={
                referral.seizureDiary.firstEventDate ??
                "Unknown"
              }
            />

            <Metric
              label="Diary end"
              value={
                referral.seizureDiary.lastEventDate ??
                "Unknown"
              }
            />
          </div>

          <p className="mt-4 text-sm leading-6 text-slate-600">
            The diary includes both seizure-labelled
            events and symptomatic or SOS-treated entries.
            Compass does not automatically classify every
            logged episode as a confirmed epileptic seizure.
          </p>
        </section>

        <section className="mt-10 print:hidden">
  <CasePanorama
    patientName={referral.patientName}
    photoSrc="/hope-profile.jpeg"
    patient={{
      patientId: referral.patientId,
      species: referral.species,
      breed: referral.breed,
      sex: referral.sex,
      dateOfBirth: referral.dateOfBirth,
      weightKg: referral.weightKg,
      workingDiagnosis:
        referral.workingDiagnosis,
    }}

    treatmentHistory={referral.medications}
    
    story={{
      totalLoggedEvents:
        referral.seizureDiary.totalLoggedEvents,

      uniqueEventDays:
        referral.seizureDiary.uniqueEventDays,

      multiEventDays:
        referral.seizureDiary.multiEventDays,

      firstEventDate:
        referral.seizureDiary.firstEventDate,

      lastEventDate:
        referral.seizureDiary.lastEventDate,

      maxEventsInOneDay:
        referral.seizureDiary.maxEventsInOneDay,

      sleepAssociatedEvents:
        referral.seizureDiary.sleepAssociatedEvents,

      symptomaticOnlyEvents:
        referral.seizureDiary.symptomaticOnlyEvents,
    }}

    drugMonitoringRecords={
      referral.therapeuticDrugMonitoring
    }
    earlyChronology={referral.earlyChronology}
      treatment={{
        daily: getCurrentMedicationText(
          phenobarbital,
          ["current"]
        ),

      sos: getCurrentMedicationText(
        levetiracetam,
        ["current-sos"]
      ),

      emergency: getCurrentMedicationText(
        emergencyPlan,
        ["current-emergency-plan"]
      ),
    }}
    
    evidence={{
      laboratoryGroups:
        referral.laboratoryGroups.length,
      videos:
        referral.videoEvidence.totalVideos,
      drugMonitoring:
        referral.therapeuticDrugMonitoring.length,
    }}

    laboratoryGroups={referral.laboratoryGroups}
    videoEvidence={referral.videoEvidence}
    questions={referral.unresolvedIssues}
  />
</section>
       
        {/* THERAPEUTIC DRUG MONITORING */}

        <section className="mt-10">
          <h2 className="text-xl font-semibold text-slate-900">
            Therapeutic drug monitoring
          </h2>

          <div className="mt-4 space-y-3">
            {referral.therapeuticDrugMonitoring.length >
            0 ? (
              referral.therapeuticDrugMonitoring.map(
                (
                  report: ReferralData["therapeuticDrugMonitoring"][number]
                ) => (
                  <div
                    key={`${report.date}-${report.title}`}
                    className="rounded-xl border border-teal-800/25 bg-teal-950/[0.025] p-5"
                  >
                    <div className="flex flex-wrap items-start justify-between gap-3">
                      <div>
                        <p className="font-semibold text-teal-950">
                          {report.title}
                        </p>

                        <p className="mt-1 text-sm text-slate-500">
                          {report.date}
                        </p>
                      </div>

                      <span className="rounded-full border border-orange-500 bg-orange-100 px-2 py-1 text-[10px] font-semibold tracking-wide text-orange-800">
                        DRUG MONITORING
                      </span>
                    </div>

                    <p className="mt-3 text-sm leading-6 text-slate-700">
                      {report.summary}
                    </p>
                  </div>
                )
              )
            ) : (
              <div className="space-y-4">
              </div>
            )}
          </div>
        </section>

        {/* LABORATORY */}

        {referral.laboratoryGroups.length > 0 && (
          <section className="mt-10 space-y-4">

            <div>
              <h2 className="text-xl font-semibold text-slate-900">
                🧪 Laboratory
              </h2>

              <p className="mt-1 text-sm text-slate-500">
                Latest result shown first. Open a group to
                review earlier results.
              </p>
            </div>

            <div className="space-y-3">

              {referral.laboratoryGroups.map((group) => {

                const content = (
                  <div className="flex items-start justify-between gap-4">
                    <div>
                      <p className="font-semibold text-teal-950">
                        {group.title}
                      </p>

                      {group.latestDate && (
                        <p className="mt-1 text-xs text-slate-500">
                          Latest · {group.latestDate}
                        </p>
                      )}

                      <p className="mt-2 text-sm leading-6 text-slate-700">
                        {group.latestCompactSummary}
                      </p>
                    </div>

                    {group.history.length > 0 && (
                      <span className="shrink-0 text-xs font-medium text-slate-500">
                        {group.history.length} earlier
                      </span>
                    )}
                  </div>
                );

                /*
                 * Only groups with history are interactive.
                 */

                if (group.history.length === 0) {
                  return (
                    <div
                      key={group.id}
                      className="rounded-xl border border-slate-200 bg-white p-5"
                    >
                      {content}
                    </div>
                  );
                }

                return (
                  <details
                    key={group.id}
                    className="rounded-xl border border-slate-200 bg-white"
                  >
                    <summary
                      className="list-none p-5"
                      style={{
                        cursor:
                          'url("/paw-cursor-pink.png") 16 16, pointer',
                      }}
                    >
                      {content}
                    </summary>

                    <div className="border-t border-slate-100 px-5 pb-5 pt-4">

                      <div className="space-y-4">

                        {group.history.map(
                          (entry, index) => (
                            <div
                              key={`${group.id}-${entry.date}-${index}`}
                              className="border-l-2 border-teal-900/20 pl-4"
                            >
                              <p className="text-xs font-medium text-slate-500">
                                {entry.date}
                              </p>

                              <p className="mt-1 text-sm leading-6 text-slate-700">
                                {entry.summary}
                              </p>
                            </div>
                          )
                        )}

                      </div>
                    </div>
                  </details>
                );
              })}

            </div>
          </section>
        )}

        {/* VIDEO EVIDENCE */}

        <section className="mt-10 space-y-4">

          <div>
            <h2 className="text-xl font-semibold text-slate-900">
              🎥 Video evidence
            </h2>

            <p className="mt-1 text-sm text-slate-500">
              Owner-recorded videos available for specialist
              review.
            </p>
          </div>

          <div className="rounded-xl border border-slate-200 bg-white">

            <div className="p-5">
              <div className="flex flex-wrap items-start justify-between gap-3">

                <div>
                  <p className="font-semibold text-teal-950">
                    {referral.videoEvidence.totalVideos} videos available
                  </p>

                  <p className="mt-1 text-sm text-slate-500">
                    {referral.videoEvidence.unlinkedVideos} currently
                    unlinked to a specific diary event
                  </p>
                </div>

                {referral.videoEvidence
                  .specialistReviewRequired && (
                  <span className="rounded-full border border-slate-300 bg-slate-50 px-2 py-1 text-[10px] font-semibold tracking-wide text-slate-700">
                    SPECIALIST REVIEW
                  </span>
                )}

              </div>
            </div>

            {referral.videoEvidence.records.length > 0 && (
              <details className="border-t border-slate-100">

                <summary
                  className="list-none px-5 py-4 text-sm font-medium text-teal-900"
                  style={{
                    cursor:
                      'url("/paw-cursor-pink.png") 16 16, pointer',
                  }}
                >
                  View video details
                </summary>

                <div className="space-y-4 px-5 pb-5">

                  {referral.videoEvidence.records.map(
                    (video) => (
                      <div
                        key={video.id}
                        className="border-l-2 border-teal-900/20 pl-4"
                      >
                        <p className="text-sm font-semibold text-slate-900">
                          {video.date} · {video.time}
                        </p>

                        <p className="mt-1 text-xs text-slate-500">
                          Duration:{" "}
                          {Math.round(
                            video.durationSeconds
                          )}{" "}
                          sec · {video.eventLinkStatus}
                        </p>

                        {video.observedEvidence && (
                          <p className="mt-2 text-sm leading-6 text-slate-700">
                            {video.observedEvidence}
                          </p>
                        )}

                        <p className="mt-2 text-xs leading-5 text-slate-500">
                          Seizure onset captured:{" "}
                          {video.seizureOnsetCaptured
                            ? "Yes"
                            : "No"}{" "}
                          · Classification assigned by
                          Compass:{" "}
                          {video.seizureClassificationAssigned
                            ? "Yes"
                            : "No"}
                        </p>
                      </div>
                    )
                  )}

                </div>
              </details>
            )}

          </div>
        </section>

        {/* UNRESOLVED ISSUES */}

        <section className="mt-10">

          <h2 className="text-xl font-semibold text-slate-900">
            Unresolved issues
          </h2>

          <ul className="mt-4 list-disc space-y-2 pl-5 text-slate-700">
            {referral.unresolvedIssues.map(
              (issue: string) => (
                <li key={issue}>
                  {issue}
                </li>
              )
            )}
          </ul>

        </section>

        {/* FOOTER */}

        <footer className="mt-10 border-t border-slate-200 pt-5 text-xs leading-5 text-slate-500">
          Compass summarizes documented evidence and
          owner-recorded history. It does not independently
          diagnose, prescribe, or alter treatment.
        </footer>

      </article>
    </main>
  );
}
/* -------------------------------------------------------
   METRIC
------------------------------------------------------- */

function Metric({
  label,
  value,
}: {
  label: string;
  value: string | number;
}) {
  return (
    <div className="print-compact-card rounded-lg border border-slate-200 p-4">

      <p className="text-xs font-medium uppercase tracking-wide text-slate-500">
        {label}
      </p>

      <p className="mt-1 text-lg font-semibold text-slate-900">
        {value}
      </p>

    </div>
  );
}