import patients from "@/data/patients";
import { loadHopeSeizures } from "@/data/loadSeizures";
import { loadHopeVideos } from "@/data/loadVideos";

import {
  buildReferralData,
  type ReferralData,
} from "@/data/buildReferralData";

type Props = {
  params: Promise<{
    id: string;
  }>;
};

export default async function ReferralPage({
  params,
}: Props) {
  const { id } = await params;

  const patient = patients.find(
    (patient) => patient.id === id
  );

  if (!patient) {
    return (
      <main className="flex min-h-screen items-center justify-center">
        <h1 className="text-3xl font-bold text-red-600">
          Patient not found
        </h1>
      </main>
    );
  }

  const seizures = loadHopeSeizures();
  const videos = loadHopeVideos();

  const referral = buildReferralData(
    patient,
    seizures,
    videos
  );

  return (
    <main className="min-h-screen bg-slate-100 px-6 py-10">
      <article className="mx-auto max-w-4xl rounded-xl bg-white p-8 shadow-lg">
        <div className="hidden print:block print:mb-4">
          <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">
            Prepared for specialist review
          </p>

          <p className="mt-1 text-xs text-slate-500">
            Generated by Compass Clinical
          </p>
        </div>

        <header className="border-b border-slate-200 pb-6">
          <p className="text-sm font-medium uppercase tracking-wide text-slate-500">
            Compass Clinical Referral
          </p>

          <h1 className="mt-2 text-4xl font-bold text-slate-900">
            {referral.patientName}
          </h1>

          <p className="mt-2 text-slate-600">
            {referral.species} · {referral.breed} · {referral.sex}
          </p>

          <p className="mt-1 text-sm text-slate-500">
            Patient ID: {referral.patientId}
          </p>
        </header>

        <section className="mt-8">
          <h2 className="text-xl font-semibold text-slate-900">
            Reason for specialist review
          </h2>

          <p className="mt-2 leading-7 text-slate-700">
            {referral.clinicalProblem}
          </p>

          {referral.workingDiagnosis && (
            <p className="mt-2 text-sm text-slate-600">
              Working diagnosis:{" "}
              <strong>
                {referral.workingDiagnosis}
              </strong>
            </p>
          )}
        </section>

        <section className="mt-8">
          <h2 className="text-xl font-semibold text-slate-900">
            Seizure diary summary
          </h2>

          <div className="print-compact-grid mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            <Metric
              label="Logged events"
              value={
                referral.seizureDiary.totalLoggedEvents
              }
            />

            <Metric
              label="Unique event days"
              value={
                referral.seizureDiary.uniqueEventDays
              }
            />

            <Metric
              label="Multi-event days"
              value={
                referral.seizureDiary.multiEventDays
              }
            />

            <Metric
              label="Maximum events/day"
              value={
                referral.seizureDiary.maxEventsInOneDay
              }
            />

            <Metric
              label="Diary start"
              value={
                referral.seizureDiary.firstEventDate ??
                "Unknown"
              }
            />

            <Metric
              label="Diary end"
              value={
                referral.seizureDiary.lastEventDate ??
                "Unknown"
              }
            />
          </div>

          <p className="mt-4 text-sm text-slate-600">
            The diary includes both seizure-labelled events
            and symptomatic or SOS-treated entries. Compass
            does not automatically classify every logged
            episode as a confirmed epileptic seizure.
          </p>
        </section>

        <section className="mt-8">
          <h2 className="text-xl font-semibold text-slate-900">
            Antiseizure medication history
          </h2>

          <div className="mt-4 space-y-3">
            {referral.medications.map(
              (
                medication: ReferralData["medications"][number],
                index: number
              ) => (
                <div
                  key={`${medication.name}-${index}`}
                  className="print-compact-card rounded-lg border border-slate-200 p-4"
                >
                  <p className="font-semibold text-slate-900">
                    {medication.name}
                  </p>

                  {medication.activeIngredient && (
                    <p className="text-sm text-slate-600">
                      {medication.activeIngredient}
                    </p>
                  )}

                  <p className="mt-2 text-sm text-slate-700">
                    {medication.dose} ·{" "}
                    {medication.frequency}
                  </p>

                  <div className="mt-2 flex flex-wrap gap-4 text-xs text-slate-500">
                    {medication.prescribedOn && (
                      <span>
                        Prescribed:{" "}
                        {medication.prescribedOn}
                      </span>
                    )}

                    {medication.status && (
                      <span>
                        Status: {medication.status}
                      </span>
                    )}
                  </div>
                </div>
              )
            )}
          </div>

          <p className="mt-4 text-sm font-medium text-amber-800">
            Current maintenance treatment requires confirmation.
          </p>
        </section>

        <section className="mt-8">
          <h2 className="text-xl font-semibold text-slate-900">
            Therapeutic drug monitoring
          </h2>

          <div className="mt-4 space-y-3">
            {referral.therapeuticDrugMonitoring.length > 0 ? (
              referral.therapeuticDrugMonitoring.map(
                (
                  report: ReferralData["therapeuticDrugMonitoring"][number]
                ) => (
                  <div
                    key={`${report.date}-${report.title}`}
                    className="rounded-lg border border-amber-200 bg-amber-50 p-4"
                  >
                    <p className="font-semibold text-amber-900">
                      {report.title}
                    </p>

                    <p className="mt-1 text-sm text-amber-800">
                      {report.date}
                    </p>

                    <p className="mt-2 text-sm leading-6 text-amber-900">
                      {report.summary}
                    </p>
                  </div>
                )
              )
            ) : (
              <p className="text-sm text-slate-600">
                No therapeutic drug monitoring data available.
              </p>
            )}
          </div>
        </section>

        <section className="mt-8">
          <h2 className="text-xl font-semibold text-slate-900">
            Video evidence
          </h2>

          <p className="mt-2 text-slate-700">
            {referral.videoEvidence.totalVideos}{" "}
            owner-recorded video clip(s) are registered as
            primary evidence.
          </p>

          <p className="mt-1 text-sm text-slate-600">
            {referral.videoEvidence.unlinkedVideos} remain
            unlinked to a specific diary event.
          </p>

          {referral.videoEvidence.specialistReviewRequired && (
            <p className="mt-2 text-sm font-medium text-blue-800">
              Formal specialist video review is required
              before assigning seizure type or clinical phase.
            </p>
          )}
        </section>

        <section className="mt-8">
          <h2 className="text-xl font-semibold text-slate-900">
            Unresolved issues
          </h2>

          <ul className="mt-4 list-disc space-y-2 pl-5 text-slate-700">
            {referral.unresolvedIssues.map(
              (issue: string) => (
                <li key={issue}>
                  {issue}
                </li>
              )
            )}
          </ul>
        </section>

        <footer className="mt-10 border-t border-slate-200 pt-5 text-xs leading-5 text-slate-500">
          Compass summarizes documented evidence and
          owner-recorded history. It does not independently
          diagnose, prescribe, or alter treatment.
        </footer>
      </article>
    </main>
  );
}

function Metric({
  label,
  value,
}: {
  label: string;
  value: string | number;
}) {
  return (
    <div className="print-compact-card rounded-lg border border-slate-200 p-4">
      <p className="text-xs font-medium uppercase tracking-wide text-slate-500">
        {label}
      </p>

      <p className="mt-1 text-lg font-semibold text-slate-900">
        {value}
      </p>
    </div>
  );
}